// js/dataStore.js
// Bootstrap data with proper structure
export const state = {
  activeDomain: "ALL", // ALL | CRM | ERP
  selectedVendorId: null,
  ui: {
    activeCapabilityId: null,
    activeProductId: null,
  },
  assignments: JSON.parse(localStorage.getItem("assignments") || "{}"),

  businessProcesses: [
    {
      id: "bp_sales",
      name: "Sales Process",
      description: "End-to-end sales lifecycle",
      order: 1,
      domain: "CRM",
    },
    {
      id: "bp_marketing",
      name: "Marketing Process",
      description: "Customer acquisition",
      order: 2,
      domain: "CRM",
    },
    {
      id: "bp_service",
      name: "Customer Service",
      description: "Support and retention",
      order: 3,
      domain: "CRM",
    },
    {
      id: "bp_field_service",
      name: "Field Service",
      description: "On-site delivery",
      order: 4,
      domain: "CRM",
    },
    {
      id: "bp_commerce",
      name: "Commerce",
      description: "E-commerce operations",
      order: 5,
      domain: "CRM",
    },
    {
      id: "bp_financial",
      name: "Financial Management",
      description: "GL to reporting",
      order: 6,
      domain: "ERP",
    },
    {
      id: "bp_supply_chain",
      name: "Supply Chain",
      description: "Procurement and logistics",
      order: 7,
      domain: "ERP",
    },
    {
      id: "bp_manufacturing",
      name: "Manufacturing",
      description: "Production planning",
      order: 8,
      domain: "ERP",
    },
    {
      id: "bp_hcm",
      name: "Human Capital",
      description: "Hire to retire",
      order: 9,
      domain: "ERP",
    },
    {
      id: "bp_project_mgmt",
      name: "Project Management",
      description: "Project execution",
      order: 10,
      domain: "ERP",
    },
  ],

  capabilities: [
    // CRM
    {
      id: "cap_lead_mgmt",
      name: "Lead Management",
      businessProcessId: "bp_sales",
      description: "Track leads from contact to conversion",
      valueProposition: "Improve conversion rates by 20-30%",
      processTypes: "core,workflow,strategic",
      color: "blue",
      order: 1,
      tags: "crm",
    },
    {
      id: "cap_opportunity_mgmt",
      name: "Opportunity Management",
      businessProcessId: "bp_sales",
      description: "Manage sales opportunities",
      valueProposition: "Increase win rates with real-time visibility",
      processTypes: "core,workflow",
      color: "blue",
      order: 2,
      tags: "crm",
    },
    {
      id: "cap_contact_mgmt",
      name: "Contact Management",
      businessProcessId: "bp_sales",
      description: "Centralized customer database",
      valueProposition: "Maintain comprehensive customer profiles",
      processTypes: "core",
      color: "blue",
      order: 3,
      tags: "crm",
    },
    {
      id: "cap_case_mgmt",
      name: "Case Management",
      businessProcessId: "bp_service",
      description: "Track and resolve customer issues",
      valueProposition: "Resolve issues faster with SLA tracking",
      processTypes: "workflow,strategic",
      color: "orange",
      order: 1,
      tags: "crm",
    },
    {
      id: "cap_campaign_mgmt",
      name: "Campaign Management",
      businessProcessId: "bp_marketing",
      description: "Multi-channel campaigns",
      valueProposition: "Improve campaign ROI and engagement",
      processTypes: "workflow,strategic",
      color: "green",
      order: 1,
      tags: "crm",
    },
    {
      id: "cap_order_mgmt",
      name: "Order Management",
      businessProcessId: "bp_commerce",
      description: "End-to-end order processing",
      valueProposition: "Fulfill orders efficiently",
      processTypes: "workflow",
      color: "teal",
      order: 1,
      tags: "crm,erp",
    },

    // ERP
    {
      id: "cap_general_ledger",
      name: "General Ledger",
      businessProcessId: "bp_financial",
      description: "Central accounting system",
      valueProposition: "Maintain accurate financial records",
      processTypes: "core,workflow",
      color: "gold",
      order: 1,
      tags: "erp",
    },
    {
      id: "cap_accounts_payable",
      name: "Accounts Payable",
      businessProcessId: "bp_financial",
      description: "Vendor invoices and payments",
      valueProposition: "Automate invoice processing",
      processTypes: "core,workflow",
      color: "gold",
      order: 2,
      tags: "erp",
    },
    {
      id: "cap_inventory_tracking",
      name: "Inventory Tracking",
      businessProcessId: "bp_supply_chain",
      description: "Real-time stock monitoring",
      valueProposition: "Optimize inventory levels",
      processTypes: "core,workflow",
      color: "slate",
      order: 1,
      tags: "erp",
    },
    {
      id: "cap_production_planning",
      name: "Production Planning",
      businessProcessId: "bp_manufacturing",
      description: "Schedule and optimize production",
      valueProposition: "Maximize throughput",
      processTypes: "workflow,strategic",
      color: "gray",
      order: 1,
      tags: "erp",
    },
    {
      id: "cap_talent_acquisition",
      name: "Talent Acquisition",
      businessProcessId: "bp_hcm",
      description: "Recruit and onboard employees",
      valueProposition: "Reduce time-to-hire",
      processTypes: "core,workflow",
      color: "teal",
      order: 1,
      tags: "erp",
    },
  ],

  vendors: [
    {
      id: "vendor_salesforce",
      name: "Salesforce",
      brandColor: "#00A1E0",
      marketPosition: "leader",
      bestFor: "Enterprises needing maximum customization",
      website: "https://www.salesforce.com",
      targetCompanySize: "mid-market,enterprise",
      overallStrengths: "Market leader|Broadest ecosystem|Strong analytics",
      overallWeaknesses: "Highest cost|Steep learning curve",
      domains: "crm",
    },
    {
      id: "vendor_microsoft",
      name: "Microsoft",
      brandColor: "#00A4EF",
      marketPosition: "leader",
      bestFor: "Organizations in Microsoft ecosystem",
      website: "https://dynamics.microsoft.com",
      targetCompanySize: "mid-market,enterprise",
      overallStrengths: "Unified CRM+ERP|Microsoft integration|Strong AI",
      overallWeaknesses: "Smaller ecosystem than Salesforce",
      domains: "crm,erp",
    },
    {
      id: "vendor_oracle",
      name: "Oracle",
      brandColor: "#F80000",
      marketPosition: "leader",
      bestFor: "Large enterprises with complex needs",
      website: "https://www.oracle.com",
      targetCompanySize: "enterprise",
      overallStrengths:
        "Enterprise-grade|Strong analytics|Deep industry solutions",
      overallWeaknesses: "High cost|Complex implementation",
      domains: "crm,erp",
    },
    {
      id: "vendor_sap",
      name: "SAP",
      brandColor: "#0FAAFF",
      marketPosition: "leader",
      bestFor: "Global enterprises",
      website: "https://www.sap.com",
      targetCompanySize: "enterprise",
      overallStrengths: "Scalability|Global compliance|Extensive ecosystem",
      overallWeaknesses: "High cost|Requires SAP expertise",
      domains: "crm,erp",
    },
  ],

  products: [
    // CRM Products
    {
      id: "prod_sf_sales_cloud",
      name: "Sales Cloud",
      vendorId: "vendor_salesforce",
      description: "Comprehensive sales automation platform",
      productType: "module",
      capabilityIds: [
        "cap_lead_mgmt",
        "cap_opportunity_mgmt",
        "cap_contact_mgmt",
      ],
      features:
        "Lead Management|Opportunity Management|Sales Forecasting|Workflow Automation",
      pricingTier: "$$$$",
      marketPosition: "leader",
      performanceMetrics: "productivityIncrease:20-30%|roi:361% over 3 years",
      deploymentModels: "cloud,hybrid",
      integrations: "Marketing Cloud|Service Cloud|Tableau",
      domains: "crm",
    },

    {
      id: "prod_sf_service_cloud",
      name: "Service Cloud",
      vendorId: "vendor_salesforce",
      description: "Customer service platform",
      productType: "module",
      capabilityIds: ["cap_case_mgmt"],
      features:
        "Case Management|Omnichannel Routing|Knowledge Base|AI Automation",
      pricingTier: "$$$$",
      marketPosition: "leader",
      performanceMetrics: "productivityIncrease:20-30%",
      deploymentModels: "cloud",
      integrations: "Sales Cloud|Einstein AI",
      domains: "crm",
    },

    {
      id: "prod_d365_sales",
      name: "Dynamics 365 Sales",
      vendorId: "vendor_microsoft",
      description: "AI-powered sales automation",
      productType: "module",
      capabilityIds: [
        "cap_lead_mgmt",
        "cap_opportunity_mgmt",
        "cap_contact_mgmt",
      ],
      features:
        "AI Insights (Copilot)|LinkedIn Integration|Sales Automation|Mobile App",
      pricingTier: "$$$",
      marketPosition: "leader",
      performanceMetrics: "productivityIncrease:15-25%",
      deploymentModels: "cloud,on-premise,hybrid",
      integrations: "Customer Service|Marketing|Power Platform|Teams",
      domains: "crm",
    },

    // ERP Products
    {
      id: "prod_d365_finance",
      name: "Dynamics 365 Finance",
      vendorId: "vendor_microsoft",
      description: "Financial management with Microsoft integration",
      productType: "module",
      capabilityIds: ["cap_general_ledger", "cap_accounts_payable"],
      features:
        "General Ledger|AP/AR|Budgeting|Cash Management|Power BI Integration",
      pricingTier: "$$$",
      marketPosition: "leader",
      performanceMetrics: "productivityIncrease:15-25%",
      deploymentModels: "cloud,on-premise,hybrid",
      integrations: "D365 Supply Chain|Power Platform",
      domains: "erp",
    },

    {
      id: "prod_oracle_fusion_financials",
      name: "Oracle Fusion Financials",
      vendorId: "vendor_oracle",
      description: "Enterprise financial management with AI",
      productType: "module",
      capabilityIds: ["cap_general_ledger", "cap_accounts_payable"],
      features:
        "General Ledger|AP/AR|AI-Driven Automation|Cash and Treasury|Revenue Management",
      pricingTier: "$$$$",
      marketPosition: "leader",
      performanceMetrics: "productivityIncrease:20-30%",
      deploymentModels: "cloud",
      integrations: "Oracle SCM|Oracle HCM|Oracle EPM",
      domains: "erp",
    },

    {
      id: "prod_sap_s4hana_finance",
      name: "SAP S/4HANA Finance",
      vendorId: "vendor_sap",
      description: "Advanced financial management for enterprises",
      productType: "module",
      capabilityIds: ["cap_general_ledger", "cap_accounts_payable"],
      features:
        "Universal Journal|In-Memory HANA|Global Compliance|Real-time Analytics",
      pricingTier: "$$$$",
      marketPosition: "leader",
      performanceMetrics: "productivityIncrease:15-25%",
      deploymentModels: "cloud,on-premise,hybrid",
      integrations: "S/4HANA Supply Chain|SAP Analytics Cloud",
      domains: "erp",
    },
  ],

  productEvaluations: [
    {
      id: "eval_sf_sales_lead",
      productId: "prod_sf_sales_cloud",
      capabilityId: "cap_lead_mgmt",
      goodFor: [
        "Enterprise deployments",
        "Complex sales cycles with multiple stakeholders",
        "Advanced analytics needs",
        "Deep customization requirements",
      ],
      notIdealFor: [
        "Small businesses with limited budgets",
        "Simple contact management needs",
        "Organizations with limited IT resources",
      ],
      bestUseCases: [
        "B2B Enterprise Sales with 6-18 month cycles",
        "Multi-channel lead capture with intelligent routing",
        "High-volume lead management with automated scoring",
      ],
      specialFeatures: [
        "Einstein AI for predictive lead scoring",
        "AppExchange ecosystem with 1000+ integrations",
        "Customer 360 unified view",
        "Mobile-first architecture",
      ],
      competitiveAdvantages: [
        "Most comprehensive ecosystem",
        "Deepest customization capabilities",
        "Strongest analytics with Tableau integration",
        "Largest community and resources",
      ],
      competitiveDisadvantages: [
        "Highest total cost of ownership",
        "Steepest learning curve",
        "Can be over-engineered for simple needs",
        "Requires ongoing admin resources",
      ],
      implementationComplexity: "high",
      typicalImplementationTime: "6-12 months",
      confidence: "high",
    },
    {
      id: "eval_d365_sales_lead",
      productId: "prod_d365_sales",
      capabilityId: "cap_lead_mgmt",
      goodFor: [
        "Organizations using Microsoft 365",
        "Companies wanting AI-driven insights (Copilot)",
        "Businesses needing CRM+ERP integration",
        "Teams using Teams/Outlook/Excel",
      ],
      notIdealFor: [
        "Organizations outside Microsoft ecosystem",
        "Companies needing extensive third-party marketplace",
        "Businesses requiring highly specialized industry solutions",
      ],
      bestUseCases: [
        "Microsoft-centric sales with Teams/Outlook integration",
        "LinkedIn-powered prospecting and social selling",
        "AI-assisted selling with Copilot",
      ],
      specialFeatures: [
        "Copilot AI for email drafting and meeting summaries",
        "Native LinkedIn Sales Navigator integration",
        "Power Platform for low-code customization",
        "Unified data model across CRM and ERP",
      ],
      competitiveAdvantages: [
        "Best Microsoft ecosystem integration",
        "Strong AI capabilities with Copilot",
        "Unified CRM+ERP platform",
        "Competitive pricing for Microsoft customers",
      ],
      competitiveDisadvantages: [
        "Smaller third-party ecosystem than Salesforce",
        "Less mature in some areas",
        "Requires Microsoft licensing strategy",
      ],
      implementationComplexity: "medium",
      typicalImplementationTime: "6-12 months",
      confidence: "high",
    },
    {
      id: "eval_d365_finance_gl",
      productId: "prod_d365_finance",
      capabilityId: "cap_general_ledger",
      goodFor: [
        "Organizations using Microsoft 365",
        "Mid-market to enterprise companies",
        "Businesses needing CRM-ERP integration",
        "Companies wanting familiar interfaces",
      ],
      notIdealFor: [
        "Organizations outside Microsoft ecosystem",
        "Companies needing most advanced features",
        "Very large complex global enterprises",
      ],
      bestUseCases: [
        "Microsoft-integrated finance with Excel/Teams workflows",
        "Unified business platform connecting finance, sales, and operations",
        "Power BI analytics for financial reporting",
      ],
      specialFeatures: [
        "Power Platform integration for customization",
        "Native Excel add-ins for budgeting",
        "Teams collaboration for financial workflows",
        "Azure AI for fraud detection",
      ],
      competitiveAdvantages: [
        "Best Microsoft ecosystem integration",
        "Familiar user interface",
        "Strong analytics with Power BI",
        "Competitive pricing for Microsoft customers",
      ],
      competitiveDisadvantages: [
        "Less comprehensive than SAP/Oracle for very large enterprises",
        "Smaller partner ecosystem",
        "May require multiple Dynamics modules",
      ],
      implementationComplexity: "medium",
      typicalImplementationTime: "6-12 months",
      confidence: "high",
    },
  ],
};

export function ensureBootstrapData() {
  console.log("✅ Bootstrap data loaded");
}
